# Generated by Django 2.0 on 2018-03-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberary', '0002_auto_20180307_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, upload_to='picture'),
        ),
    ]
