# Generated by Django 2.0.3 on 2018-03-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberary', '0003_auto_20180308_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, upload_to='picture/'),
        ),
    ]
